import plugin from "tailwindcss/plugin";
/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{tsx,ts,jsx,js}"],
  theme: {
    extend: {
      fontFamily: {
        inter: ["Inter", "sans-serif"],
      },
    },
    colors: {
      base: {
        neutral: "hsla(var(--base-neutral))",
        accent: "hsla(var(--base-accent))",
        success: "hsla(var(--base-success))",
        warning: "hsla(var(--base-warning))",
        error: "hsla(var(--base-error))",
        info: "hsla(var(--base-info))",
        "status-01": "hsla(var(--base-status-01))",
        "status-02": "hsla(var(--base-status-02))",
        "status-03": "hsla(var(--base-status-03))",
        "status-04": "hsla(var(--base-status-04))",
        "status-05": "hsla(var(--base-status-05))",
        "status-06": "hsla(var(--base-status-06))",
      },
      fg: {
        DEFAULT: "hsla(var(--fg-default))",
        soft: "hsla(var(--fg-soft))",
        muted: "hsla(var(--fg-muted))",
        disabled: "hsla(var(--fg-disabled))",
      },
      bg: {
        surface1: "hsla(var(--bg-surface1))",
        surface2: "hsla(var(--bg-surface2))",
        surface3: "hsla(var(--bg-surface3))",
        surface4: "hsla(var(--bg-surface4))",
        surface5: "hsla(var(--bg-surface5))",
        page: "hsla(var(--bg-page))",
        disabled: "hsla(var(--bg-disabled))",
        "elevated-0": "hsla(var(--bg-elevated-0))",
        "elevated-s": "hsla(var(--bg-elevated-s))",
        "elevated-m": "hsla(var(--bg-elevated-m))",
        "elevated-l": "hsla(var(--bg-elevated-l))",
        "elevated-xl": "hsla(var(--bg-elevated-xl))",
      },
      border: {
        DEFAULT: "hsla(var(--border-default))",
        soft: "hsla(var(--border-soft))",
        muted: "hsla(var(--border-muted))",
      },
      accent: {
        DEFAULT: "hsla(var(--accent-default))",
        soft: "hsla(var(--accent-soft))",
        muted: "hsla(var(--accent-muted))",
        hover: "hsla(var(--accent-hover))",
        active: "hsla(var(--accent-active))",
        container: "hsla(var(--accent-container-default))",
        "container-soft": "hsla(var(--accent-container-soft))",
        "container-muted": "hsla(var(--accent-container-muted))",
        "container-hover": "hsla(var(--accent-container-hover))",
        "container-active": "hsla(var(--accent-container-active))",
        "on-container": "hsla(var(--accent-on-container))",
        "on-accent": "hsla(var(--accent-on-accent))",
        1000: "hsla(var(--accent-1000))",
        990: "hsla(var(--accent-990))",
        950: "hsla(var(--accent-950))",
        925: "hsla(var(--accent-925))",
        900: "hsla(var(--accent-900))",
        800: "hsla(var(--accent-800))",
        700: "hsla(var(--accent-700))",
        600: "hsla(var(--accent-600))",
        500: "hsla(var(--accent-500))",
        400: "hsla(var(--accent-400))",
        300: "hsla(var(--accent-300))",
        200: "hsla(var(--accent-200))",
        100: "hsla(var(--accent-100))",
        50: "hsla(var(--accent-50))",
        25: "hsla(var(--accent-25))",
        10: "hsla(var(--accent-10))",
        0: "hsla(var(--accent-0))",
      },
      neutral: {
        DEFAULT: "hsla(var(--neutral-default))",
        soft: "hsla(var(--neutral-soft))",
        muted: "hsla(var(--neutral-muted))",
        hover: "hsla(var(--neutral-hover))",
        active: "hsla(var(--neutral-active))",
        container: "hsla(var(--neutral-container-default))",
        "container-soft": "hsla(var(--neutral-container-soft))",
        "container-muted": "hsla(var(--neutral-container-muted))",
        "container-hover": "hsla(var(--neutral-container-hover))",
        "container-active": "hsla(var(--neutral-container-active))",
        "on-container": "hsla(var(--neutral-on-container))",
        "on-neutral": "hsla(var(--neutral-on-neutral))",
        1000: "hsla(var(--neutral-1000))",
        990: "hsla(var(--neutral-990))",
        950: "hsla(var(--neutral-950))",
        925: "hsla(var(--neutral-925))",
        900: "hsla(var(--neutral-900))",
        800: "hsla(var(--neutral-800))",
        700: "hsla(var(--neutral-700))",
        600: "hsla(var(--neutral-600))",
        500: "hsla(var(--neutral-500))",
        400: "hsla(var(--neutral-400))",
        300: "hsla(var(--neutral-300))",
        200: "hsla(var(--neutral-200))",
        100: "hsla(var(--neutral-100))",
        50: "hsla(var(--neutral-50))",
        25: "hsla(var(--neutral-25))",
        10: "hsla(var(--neutral-10))",
        0: "hsla(var(--neutral-0))",
      },
      success: {
        DEFAULT: "hsla(var(--success-default))",
        soft: "hsla(var(--success-soft))",
        muted: "hsla(var(--success-muted))",
        hover: "hsla(var(--success-hover))",
        active: "hsla(var(--success-active))",
        container: "hsla(var(--success-container-default))",
        "container-soft": "hsla(var(--success-container-soft))",
        "container-muted": "hsla(var(--success-container-muted))",
        "container-hover": "hsla(var(--success-container-hover))",
        "container-active": "hsla(var(--success-container-active))",
        "on-container": "hsla(var(--success-on-container))",
        "on-success": "hsla(var(--success-on-success))",
        1000: "hsla(var(--success-1000))",
        990: "hsla(var(--success-990))",
        950: "hsla(var(--success-950))",
        925: "hsla(var(--success-925))",
        900: "hsla(var(--success-900))",
        800: "hsla(var(--success-800))",
        700: "hsla(var(--success-700))",
        600: "hsla(var(--success-600))",
        500: "hsla(var(--success-500))",
        400: "hsla(var(--success-400))",
        300: "hsla(var(--success-300))",
        200: "hsla(var(--success-200))",
        100: "hsla(var(--success-100))",
        50: "hsla(var(--success-50))",
        25: "hsla(var(--success-25))",
        10: "hsla(var(--success-10))",
        0: "hsla(var(--success-0))",
      },
      warning: {
        DEFAULT: "hsla(var(--warning-default))",
        soft: "hsla(var(--warning-soft))",
        muted: "hsla(var(--warning-muted))",
        hover: "hsla(var(--warning-hover))",
        active: "hsla(var(--warning-active))",
        container: "hsla(var(--warning-container-default))",
        "container-soft": "hsla(var(--warning-container-soft))",
        "container-muted": "hsla(var(--warning-container-muted))",
        "container-hover": "hsla(var(--warning-container-hover))",
        "container-active": "hsla(var(--warning-container-active))",
        "on-container": "hsla(var(--warning-on-container))",
        "on-warning": "hsla(var(--warning-on-warning))",
        1000: "hsla(var(--warning-1000))",
        990: "hsla(var(--warning-990))",
        950: "hsla(var(--warning-950))",
        925: "hsla(var(--warning-925))",
        900: "hsla(var(--warning-900))",
        800: "hsla(var(--warning-800))",
        700: "hsla(var(--warning-700))",
        600: "hsla(var(--warning-600))",
        500: "hsla(var(--warning-500))",
        400: "hsla(var(--warning-400))",
        300: "hsla(var(--warning-300))",
        200: "hsla(var(--warning-200))",
        100: "hsla(var(--warning-100))",
        50: "hsla(var(--warning-50))",
        25: "hsla(var(--warning-25))",
        10: "hsla(var(--warning-10))",
        0: "hsla(var(--warning-0))",
      },
      error: {
        DEFAULT: "hsla(var(--error-default))",
        soft: "hsla(var(--error-soft))",
        muted: "hsla(var(--error-muted))",
        hover: "hsla(var(--error-hover))",
        active: "hsla(var(--error-active))",
        container: "hsla(var(--error-container-default))",
        "container-soft": "hsla(var(--error-container-soft))",
        "container-muted": "hsla(var(--error-container-muted))",
        "container-hover": "hsla(var(--error-container-hover))",
        "container-active": "hsla(var(--error-container-active))",
        "on-container": "hsla(var(--error-on-container))",
        "on-error": "hsla(var(--error-on-error))",
        1000: "hsla(var(--error-1000))",
        990: "hsla(var(--error-990))",
        950: "hsla(var(--error-950))",
        925: "hsla(var(--error-925))",
        900: "hsla(var(--error-900))",
        800: "hsla(var(--error-800))",
        700: "hsla(var(--error-700))",
        600: "hsla(var(--error-600))",
        500: "hsla(var(--error-500))",
        400: "hsla(var(--error-400))",
        300: "hsla(var(--error-300))",
        200: "hsla(var(--error-200))",
        100: "hsla(var(--error-100))",
        50: "hsla(var(--error-50))",
        25: "hsla(var(--error-25))",
        10: "hsla(var(--error-10))",
        0: "hsla(var(--error-0))",
      },
      info: {
        DEFAULT: "hsla(var(--info-default))",
        soft: "hsla(var(--info-soft))",
        muted: "hsla(var(--info-muted))",
        hover: "hsla(var(--info-hover))",
        active: "hsla(var(--info-active))",
        container: "hsla(var(--info-container-default))",
        "container-soft": "hsla(var(--info-container-soft))",
        "container-muted": "hsla(var(--info-container-muted))",
        "container-hover": "hsla(var(--info-container-hover))",
        "container-active": "hsla(var(--info-container-active))",
        "on-container": "hsla(var(--info-on-container))",
        "on-info": "hsla(var(--info-on-info))",
        1000: "hsla(var(--info-1000))",
        990: "hsla(var(--info-990))",
        950: "hsla(var(--info-950))",
        925: "hsla(var(--info-925))",
        900: "hsla(var(--info-900))",
        800: "hsla(var(--info-800))",
        700: "hsla(var(--info-700))",
        600: "hsla(var(--info-600))",
        500: "hsla(var(--info-500))",
        400: "hsla(var(--info-400))",
        300: "hsla(var(--info-300))",
        200: "hsla(var(--info-200))",
        100: "hsla(var(--info-100))",
        50: "hsla(var(--info-50))",
        25: "hsla(var(--info-25))",
        10: "hsla(var(--info-10))",
        0: "hsla(var(--info-0))",
      },
      "status-01": {
        DEFAULT: "hsla(var(--status-01-default))",
        soft: "hsla(var(--status-01-soft))",
        muted: "hsla(var(--status-01-muted))",
        hover: "hsla(var(--status-01-hover))",
        active: "hsla(var(--status-01-active))",
        container: "hsla(var(--status-01-container-default))",
        "container-soft": "hsla(var(--status-01-container-soft))",
        "container-muted": "hsla(var(--status-01-container-muted))",
        "container-hover": "hsla(var(--status-01-container-hover))",
        "container-active": "hsla(var(--status-01-container-active))",
        "on-container": "hsla(var(--status-01-on-container))",
        "on-status-01": "hsla(var(--status-01-on-status-01))",
        1000: "hsla(var(--status-01-1000))",
        990: "hsla(var(--status-01-990))",
        950: "hsla(var(--status-01-950))",
        925: "hsla(var(--status-01-925))",
        900: "hsla(var(--status-01-900))",
        800: "hsla(var(--status-01-800))",
        700: "hsla(var(--status-01-700))",
        600: "hsla(var(--status-01-600))",
        500: "hsla(var(--status-01-500))",
        400: "hsla(var(--status-01-400))",
        300: "hsla(var(--status-01-300))",
        200: "hsla(var(--status-01-200))",
        100: "hsla(var(--status-01-100))",
        50: "hsla(var(--status-01-50))",
        25: "hsla(var(--status-01-25))",
        10: "hsla(var(--status-01-10))",
        0: "hsla(var(--status-01-0))",
      },
      "status-02": {
        DEFAULT: "hsla(var(--status-02-default))",
        soft: "hsla(var(--status-02-soft))",
        muted: "hsla(var(--status-02-muted))",
        hover: "hsla(var(--status-02-hover))",
        active: "hsla(var(--status-02-active))",
        container: "hsla(var(--status-02-container-default))",
        "container-soft": "hsla(var(--status-02-container-soft))",
        "container-muted": "hsla(var(--status-02-container-muted))",
        "container-hover": "hsla(var(--status-02-container-hover))",
        "container-active": "hsla(var(--status-02-container-active))",
        "on-container": "hsla(var(--status-02-on-container))",
        "on-status-02": "hsla(var(--status-02-on-status-02))",
        1000: "hsla(var(--status-02-1000))",
        990: "hsla(var(--status-02-990))",
        950: "hsla(var(--status-02-950))",
        925: "hsla(var(--status-02-925))",
        900: "hsla(var(--status-02-900))",
        800: "hsla(var(--status-02-800))",
        700: "hsla(var(--status-02-700))",
        600: "hsla(var(--status-02-600))",
        500: "hsla(var(--status-02-500))",
        400: "hsla(var(--status-02-400))",
        300: "hsla(var(--status-02-300))",
        200: "hsla(var(--status-02-200))",
        100: "hsla(var(--status-02-100))",
        50: "hsla(var(--status-02-50))",
        25: "hsla(var(--status-02-25))",
        10: "hsla(var(--status-02-10))",
        0: "hsla(var(--status-02-0))",
      },
      "status-03": {
        DEFAULT: "hsla(var(--status-03-default))",
        soft: "hsla(var(--status-03-soft))",
        muted: "hsla(var(--status-03-muted))",
        hover: "hsla(var(--status-03-hover))",
        active: "hsla(var(--status-03-active))",
        container: "hsla(var(--status-03-container-default))",
        "container-soft": "hsla(var(--status-03-container-soft))",
        "container-muted": "hsla(var(--status-03-container-muted))",
        "container-hover": "hsla(var(--status-03-container-hover))",
        "container-active": "hsla(var(--status-03-container-active))",
        "on-container": "hsla(var(--status-03-on-container))",
        "on-status-03": "hsla(var(--status-03-on-status-03))",
        1000: "hsla(var(--status-03-1000))",
        990: "hsla(var(--status-03-990))",
        950: "hsla(var(--status-03-950))",
        925: "hsla(var(--status-03-925))",
        900: "hsla(var(--status-03-900))",
        800: "hsla(var(--status-03-800))",
        700: "hsla(var(--status-03-700))",
        600: "hsla(var(--status-03-600))",
        500: "hsla(var(--status-03-500))",
        400: "hsla(var(--status-03-400))",
        300: "hsla(var(--status-03-300))",
        200: "hsla(var(--status-03-200))",
        100: "hsla(var(--status-03-100))",
        50: "hsla(var(--status-03-50))",
        25: "hsla(var(--status-03-25))",
        10: "hsla(var(--status-03-10))",
        0: "hsla(var(--status-03-0))",
      },
      "status-04": {
        DEFAULT: "hsla(var(--status-04-default))",
        soft: "hsla(var(--status-04-soft))",
        muted: "hsla(var(--status-04-muted))",
        hover: "hsla(var(--status-04-hover))",
        active: "hsla(var(--status-04-active))",
        container: "hsla(var(--status-04-container-default))",
        "container-soft": "hsla(var(--status-04-container-soft))",
        "container-muted": "hsla(var(--status-04-container-muted))",
        "container-hover": "hsla(var(--status-04-container-hover))",
        "container-active": "hsla(var(--status-04-container-active))",
        "on-container": "hsla(var(--status-04-on-container))",
        "on-status-04": "hsla(var(--status-04-on-status-04))",
        1000: "hsla(var(--status-04-1000))",
        990: "hsla(var(--status-04-990))",
        950: "hsla(var(--status-04-950))",
        925: "hsla(var(--status-04-925))",
        900: "hsla(var(--status-04-900))",
        800: "hsla(var(--status-04-800))",
        700: "hsla(var(--status-04-700))",
        600: "hsla(var(--status-04-600))",
        500: "hsla(var(--status-04-500))",
        400: "hsla(var(--status-04-400))",
        300: "hsla(var(--status-04-300))",
        200: "hsla(var(--status-04-200))",
        100: "hsla(var(--status-04-100))",
        50: "hsla(var(--status-04-50))",
        25: "hsla(var(--status-04-25))",
        10: "hsla(var(--status-04-10))",
        0: "hsla(var(--status-04-0))",
      },
      "status-05": {
        DEFAULT: "hsla(var(--status-05-default))",
        soft: "hsla(var(--status-05-soft))",
        muted: "hsla(var(--status-05-muted))",
        hover: "hsla(var(--status-05-hover))",
        active: "hsla(var(--status-05-active))",
        container: "hsla(var(--status-05-container-default))",
        "container-soft": "hsla(var(--status-05-container-soft))",
        "container-muted": "hsla(var(--status-05-container-muted))",
        "container-hover": "hsla(var(--status-05-container-hover))",
        "container-active": "hsla(var(--status-05-container-active))",
        "on-container": "hsla(var(--status-05-on-container))",
        "on-status-05": "hsla(var(--status-05-on-status-05))",
        1000: "hsla(var(--status-05-1000))",
        990: "hsla(var(--status-05-990))",
        950: "hsla(var(--status-05-950))",
        925: "hsla(var(--status-05-925))",
        900: "hsla(var(--status-05-900))",
        800: "hsla(var(--status-05-800))",
        700: "hsla(var(--status-05-700))",
        600: "hsla(var(--status-05-600))",
        500: "hsla(var(--status-05-500))",
        400: "hsla(var(--status-05-400))",
        300: "hsla(var(--status-05-300))",
        200: "hsla(var(--status-05-200))",
        100: "hsla(var(--status-05-100))",
        50: "hsla(var(--status-05-50))",
        25: "hsla(var(--status-05-25))",
        10: "hsla(var(--status-05-10))",
        0: "hsla(var(--status-05-0))",
      },
      "status-06": {
        DEFAULT: "hsla(var(--status-06-default))",
        soft: "hsla(var(--status-06-soft))",
        muted: "hsla(var(--status-06-muted))",
        hover: "hsla(var(--status-06-hover))",
        active: "hsla(var(--status-06-active))",
        container: "hsla(var(--status-06-container-default))",
        "container-soft": "hsla(var(--status-06-container-soft))",
        "container-muted": "hsla(var(--status-06-container-muted))",
        "container-hover": "hsla(var(--status-06-container-hover))",
        "container-active": "hsla(var(--status-06-container-active))",
        "on-container": "hsla(var(--status-06-on-container))",
        "on-status-06": "hsla(var(--status-06-on-status-06))",
        1000: "hsla(var(--status-06-1000))",
        990: "hsla(var(--status-06-990))",
        950: "hsla(var(--status-06-950))",
        925: "hsla(var(--status-06-925))",
        900: "hsla(var(--status-06-900))",
        800: "hsla(var(--status-06-800))",
        700: "hsla(var(--status-06-700))",
        600: "hsla(var(--status-06-600))",
        500: "hsla(var(--status-06-500))",
        400: "hsla(var(--status-06-400))",
        300: "hsla(var(--status-06-300))",
        200: "hsla(var(--status-06-200))",
        100: "hsla(var(--status-06-100))",
        50: "hsla(var(--status-06-50))",
        25: "hsla(var(--status-06-25))",
        10: "hsla(var(--status-06-10))",
        0: "hsla(var(--status-06-0))",
      },
      static: {
        white: "hsla(var(--static-white))",
        black: "hsla(var(--static-black))",
      },
    },
  },
  plugins: [
    plugin(function({ addComponents }) {
      addComponents({
        ".display-large": {
          "@apply text-[3rem] leading-[3.25rem] font-medium text-fg": {},
        },

        ".display-large-strong": {
          "@apply text-[3rem] leading-[3.25rem] font-bold text-fg": {},
        },

        ".display-medium": {
          "@apply text-[2.625rem] leading-[2.75rem] font-medium text-fg": {},
        },

        ".display-medium-strong": {
          "@apply text-[2.625rem] leading-[2.75rem] font-bold text-fg": {},
        },

        ".display-small": {
          "@apply text-[2rem] leading-[2.75rem] font-medium text-fg": {},
        },

        ".display-small-strong": {
          "@apply text-[2rem] leading-[2.75rem] font-bold text-fg": {},
        },

        ".heading-1": {
          "@apply text-[1.75rem] leading-[2rem] font-bold text-fg": {},
        },

        ".heading-2": {
          "@apply text-[1.375rem] leading-[1.5rem] font-bold text-fg": {},
        },

        ".heading-3": {
          "@apply text-[1.125rem] leading-[1.25rem] font-bold text-fg": {},
        },

        ".heading-4": {
          "@apply text-[1rem] leading-[1.25rem] font-bold text-fg": {},
        },

        ".heading-5": {
          "@apply text-[0.875rem] leading-[1.25rem] font-bold text-fg": {},
        },

        ".body-large": {
          "@apply text-[1.125rem] leading-[1.625rem] font-normal text-fg": {},
        },

        ".body-large-strong": {
          "@apply text-[1.125rem] leading-[1.625rem] font-medium text-fg": {},
        },

        ".body-medium": {
          "@apply text-[1rem] leading-[1.5rem] font-normal text-fg": {},
        },

        ".body-medium-strong": {
          "@apply text-[1rem] leading-[1.5rem] font-medium text-fg": {},
        },

        ".body-small": {
          "@apply text-[0.875rem] leading-[1.25rem] font-normal text-fg": {},
        },

        ".body-small-strong": {
          "@apply text-[0.875rem] leading-[1.25rem] font-medium text-fg": {},
        },

        ".description-large": {
          "@apply text-[0.75rem] leading-[1rem] font-normal text-fg": {},
        },

        ".description-large-strong": {
          "@apply text-[0.75rem] leading-[1rem] font-medium text-fg": {},
        },

        ".description-medium": {
          "@apply text-[0.688rem] leading-[1rem] tracking-[0.0125rem] font-normal text-fg":
            {},
        },

        ".description-medium-strong": {
          "@apply text-[0.688rem] leading-[1rem] tracking-[0.0125rem] font-medium text-fg":
            {},
        },

        ".description-small": {
          "@apply text-[0.625rem] leading-[0.75rem] tracking-[0.025rem] font-normal text-fg":
            {},
        },

        ".description-small-strong": {
          "@apply text-[0.625rem] leading-[0.75rem] tracking-[0.025rem] font-medium text-fg":
            {},
        },
      });
    }),
  ],
};
